name: Process Subscriptions Separately

on:
  schedule:
    - cron: '*/9 * * * *' # Запуск каждые 9 минут
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  process-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Задача 1: Первая ссылка -> result1.txt
      - name: Process First Source
        env:
          FIRST_URL: ${{ secrets.ZIENG_URL }}
        run: |
          curl -sL "$FIRST_URL" | grep "reality" > reality.txt || true

      # Задача 2: Вторая ссылка -> result2.txt
      - name: Process Second Source
        env:
          SECOND_URL: ${{ secrets.BL }}
        run: |
          curl -sL "$SECOND_URL" | grep "reality" > reality_bl.txt || true

      # Шаг 3: Сохраняем оба файла в репозиторий
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@github.com"
          git add reality.txt reality_bl.txt
          git diff-index --quiet HEAD || git commit -m "Update reality profiles for both sources"
          git push
